# It is to be run as follows from the current directory
# ansible-playbook kraft-mode-start-kafka-cluster.yml
---
- hosts: kraft_servers
  vars:

    kafka_version : "2.8.0"

  remote_user: root
  tasks:

  - name: Starting up Apache Kafka Cluster Components (Brokers and Controllers)
    command: /usr/local/software/kafka/bin/kafka-server-start.sh -daemon /usr/local/software/kafka/config/kraft/software.properties
    args:
      chdir: /usr/local/software/kafka