# It is to be run as follows from the current directory
# ansible-playbook kraft-mode-format-storage-directories.yml
---
- hosts: kraft_servers
  vars:

    reset_java_home : "reset"
    artifact_download_location: "/root/Ansible/Downloads/"
    local_file_path: "files/without-zookeeper"
    kafka_cluster_id: "S2IJh7ozSsuE71h5uuGXzg" # output from /bin/kafka-storage.sh random-uuid

    common_tarballs:
      - { name : 'kafka', group : 'oss', user : 'root', permissions : '0775', location : 'kafka', url : 'https://downloads.apache.org/kafka/2.8.0/kafka_2.12-2.8.0.tgz'}

    tarball_installers:
      - { name: 'kafka', group: 'oss', owner: 'kafka', file: 'kafka_2.12-2.8.0.tgz', dest: '/usr/local/software'}

  remote_user: root
  tasks:

  - name: Formatting Storage Directories
    command: ./bin/kafka-storage.sh format --ignore-formatted -t {{ kafka_cluster_id }} -c ./config/kraft/software.properties
    args:
      chdir: /usr/local/software/kafka

