# It is to be run as follows from the current directory
# ansible-playbook legacy--start-kafka-cluster.yml
---
- hosts: legacy_brokers
  vars:

    kafka_version : "2.8.0"

  remote_user: root
  tasks:

  - name: Starting up Apache Kafka Cluster Components
    command: ./bin/kafka-server-start.sh -daemon /usr/local/software/kafka/config/software.properties
    args:
      chdir: /usr/local/software/kafka