# It is to be run as follows from the current directory
# ansible-playbook legacy-start-zookeeper.yml
---
- hosts: legacy_zookeepers
  vars:

    kafka_version : "2.8.0"

  remote_user: root
  tasks:

  - name: Starting up Apache Zookeeper Cluster
    command: ./bin/zookeeper-server-start.sh -daemon /usr/local/software/kafka/config/software.properties
    args:
      chdir: /usr/local/software/kafka