# It is to be run as follows from the current directory
# ansible-playbook legacy-stop-zookeeper.yml
---
- hosts: legacy_zookeepers
  vars:

    kafka_version : "2.8.0"

  remote_user: root
  tasks:

  - name: Stopping Legacy Apache Zookeeper Brokers
    command: ./bin/zookeeper-server-stop.sh
    args:
      chdir: /usr/local/software/kafka