# It is to be run as follows from the current directory
# ansible-playbook legacy-stop-kafka-cluster.yml
---
- hosts: legacy_brokers
  vars:

    kafka_version : "2.8.0"

  remote_user: root
  tasks:

  - name: Stopping Legacy Apache Kafka Brokers
    command: ./bin/kafka-server-stop.sh
    args:
      chdir: /usr/local/software/kafka